package ai

import (
	"fmt"
	"strings"
)

// --- MUGEN Code Templates ---
// These produce valid Ikemen GO / MUGEN state controller code.

// enemyFunc returns the optimal enemynear string with target tracking if available.
func enemyFunc(config *AIConfig) string {
	if targetVar, ok := config.VarAllocation["TargetIndex"]; ok && targetVar > 0 {
		return fmt.Sprintf("enemynear(var(%d))", targetVar)
	}
	return "enemynear"
}

// aiHeader generates the opening comment block and AI activation setup.
func aiHeader(config *AIConfig) string {
	return fmt.Sprintf(`
;===== IKEMEN-AI-PATCHER START =====
;==============================================================================
; BOSS-LEVEL AI — AUTO-GENERATED by ikemen-ai-patcher
; Character: %s
; Normals: %d | Specials: %d | Hypers: %d
; Combo Chains Detected: %d
; AI Vars: cooldown=var(%d), strategy=var(%d), combo=var(%d), rand=var(%d), track=var(%d)
;==============================================================================

; -------------------------------------------------------
; AI ACTIVATION CHECK
; All AI controllers below require: %s
; -------------------------------------------------------
`,
		config.Analysis.CharName,
		len(config.Analysis.Normals),
		len(config.Analysis.Specials),
		len(config.Analysis.Hypers),
		len(config.Analysis.ComboChains),
		config.CooldownVar, config.StrategyVar, config.ComboTrackVar,
		config.RandSeedVar, config.StateTrackVar,
		config.AIActivation,
	)
}

// aiFooter generates the closing marker.
func aiFooter() string {
	return "\n;===== IKEMEN-AI-PATCHER END =====\n"
}

// cooldownTimerBlock generates the anti-spam cooldown timer controller.
func cooldownTimerBlock(config *AIConfig) string {
	return fmt.Sprintf(`
; -------------------------------------------------------
; ANTI-SPAM COOLDOWN TIMER
; Decrements each tick. AI cannot use the same move until cooldown = 0.
; -------------------------------------------------------
[State -1, AI Cooldown Timer]
type = VarAdd
triggerall = %s
triggerall = var(%d) > 0
trigger1 = 1
v = %d
value = -1

`, config.AIActivation, config.CooldownVar, config.CooldownVar)
}

// strategyBlock generates the Layer 2 strategy selection controller.
func strategyBlock(config *AIConfig) string {
	en := enemyFunc(config)
	return fmt.Sprintf(`
; -------------------------------------------------------
; LAYER 2: STRATEGY SELECTION
; Picks strategy based on enemy state and randomization.
; 0=OFFENSE, 1=DEFENSE, 2=PUNISH, 3=BAIT
; -------------------------------------------------------

; Reset strategy each tick for dynamic adaptation
[State -1, AI Strategy Reset]
type = VarSet
triggerall = %s
trigger1 = 1
v = %d
value = 0

; PUNISH: Enemy is in recovery / whiffed attack (HIGHEST PRIORITY)
[State -1, AI Strategy: PUNISH]
type = VarSet
triggerall = %s
triggerall = %s, MoveType = A
triggerall = %s, GetHitVar(HitTime) <= 0
trigger1 = %s, AnimTime < -5
trigger2 = %s, ctrl = 0
v = %d
value = 2

; DEFENSE: Enemy is actively attacking us
[State -1, AI Strategy: DEFENSE]
type = VarSet
triggerall = %s
triggerall = var(%d) != 2
triggerall = %s, MoveType = A
trigger1 = InGuardDist
trigger2 = %s, GetHitVar(HitTime) > 0
v = %d
value = 1

; BAIT: Occasional fake-out behavior (randomized ~15%% chance)
[State -1, AI Strategy: BAIT]
type = VarSet
triggerall = %s
triggerall = var(%d) = 0
triggerall = Random < 150
trigger1 = P2BodyDist X = [80, 200]
v = %d
value = 3

`, config.AIActivation, config.StrategyVar,
		config.AIActivation, en, en, en, en, config.StrategyVar,
		config.AIActivation, config.StrategyVar, en, en, config.StrategyVar,
		config.AIActivation, config.StrategyVar, config.StrategyVar,
	)
}

// randomSeedBlock generates randomization controller to avoid deterministic AI.
func randomSeedBlock(config *AIConfig) string {
	return fmt.Sprintf(`
; -------------------------------------------------------
; RANDOMIZATION SEED
; Updates each tick to create non-deterministic behavior.
; -------------------------------------------------------
[State -1, AI Random Seed]
type = VarSet
triggerall = %s
trigger1 = 1
v = %d
value = Random %% 1000

`, config.AIActivation, config.RandSeedVar)
}

// memoryInitBlock generates Phase 4 tracking variables
func memoryInitBlock(config *AIConfig) string {
	en := enemyFunc(config)
	var sb strings.Builder
	sb.WriteString("\n; -------------------------------------------------------\n")
	sb.WriteString("; PHASE 4: MEMORY AI TRACKING\n")
	sb.WriteString("; -------------------------------------------------------\n")

	if xvelFvar, ok := config.FvarAllocation["EnemyXVel"]; ok {
		sb.WriteString(fmt.Sprintf(`
[State -1, Track Enemy X Velocity]
type = VarSet
trigger1 = %s
trigger1 = !IsHelper
fvar(%d) = %s, Vel X
`, config.AIActivation, xvelFvar, en))
	}

	if jumpFvar, ok := config.FvarAllocation["EnemyJumpCount"]; ok {
		sb.WriteString(fmt.Sprintf(`
[State -1, Track Enemy Jump]
type = VarAdd
triggerall = %s
triggerall = RoundState = 2
triggerall = %s, StateType = A
trigger1 = %s, Time = 1
fvar(%d) = 1

[State -1, Decay Enemy Jump]
type = VarAdd
triggerall = %s
triggerall = RoundState = 2
triggerall = %s, StateType != A
trigger1 = GameTime %% 60 = 0
fvar(%d) = -1

[State -1, Clamp Enemy Jump Min]
type = VarSet
trigger1 = fvar(%d) < 0
fvar(%d) = 0
`, config.AIActivation, en, en, jumpFvar, config.AIActivation, en, jumpFvar, jumpFvar, jumpFvar))
	}

	return sb.String()
}

// generateCnsHelpers creates the dummy Statedefs required for background AI Helpers
func generateCnsHelpers(config *AIConfig) string {
	en := enemyFunc(config)
	guardFvar := 15
	if config != nil {
		if val, ok := config.FvarAllocation["GuardCheck"]; ok {
			guardFvar = val
		}
	}

	return fmt.Sprintf(`
;===== IKEMEN-AI-PATCHER START =====
; -------------------------------------------------------
; PHASE 4: BACKGROUND AI HELPERS
; -------------------------------------------------------

[Statedef 9740]
type = S
movetype = I
physics = N
anim = 9741 ; Dummy animation 
ctrl = 0

[State 9740, Invisible]
type = AssertSpecial
trigger1 = 1
flag = invisible
flag2 = noshadow

[State 9740, NotHitBy]
type = NotHitBy
trigger1 = 1
value = SCA
time = -1

[State 9740, Bind]
type = BindToParent
trigger1 = 1
time = 1
pos = 0,0

[State 9740, Guard Check]
type = ParentVarSet
trigger1 = parent, %s, StateType = A
trigger2 = parent, %s, StateNo != 0
fvar(%d) = 1 ; Guard_Check_fvar

[Statedef 33333333]
type = S
movetype = I
physics = N
anim = 9741
ctrl = 0

[State 33333, Invisible]
type = AssertSpecial
trigger1 = 1
flag = invisible
flag2 = noshadow
[State 33333, NotHitBy]
type = NotHitBy
trigger1 = 1
value = SCA
time = -1
[State 33333, Bind]
type = BindToParent
trigger1 = 1
time = 1
pos = 0,0
;===== IKEMEN-AI-PATCHER END =====
`, en, en, guardFvar)
}

// generateAttackBlock generates a single attack ChangeState controller.
func generateAttackBlock(config *AIConfig, stateID int, label, strategy, distCond, extraTrigger string, cooldownSet int, randThreshold int) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("\n; --- %s (State %d) ---\n", label, stateID))
	sb.WriteString(fmt.Sprintf("[State -1, AI %s: %s]\n", strategy, label))
	sb.WriteString("type = ChangeState\n")
	sb.WriteString(fmt.Sprintf("value = %d\n", stateID))
	sb.WriteString(fmt.Sprintf("triggerall = %s\n", config.AIActivation))
	sb.WriteString("triggerall = RoundState = 2\n")
	sb.WriteString(fmt.Sprintf("triggerall = var(%d) = 0\n", config.CooldownVar)) // Anti-spam
	sb.WriteString(fmt.Sprintf("triggerall = var(%d) != %d\n", config.StateTrackVar, stateID)) // No repeat

	// Randomization gate
	if randThreshold > 0 {
		sb.WriteString(fmt.Sprintf("triggerall = Random < %d\n", randThreshold))
	}

	// Strategy condition
	switch strategy {
	case "PUNISH":
		sb.WriteString(fmt.Sprintf("triggerall = var(%d) = 2\n", config.StrategyVar))
	case "OFFENSE":
		sb.WriteString(fmt.Sprintf("triggerall = var(%d) = 0\n", config.StrategyVar))
	case "DEFENSE":
		sb.WriteString(fmt.Sprintf("triggerall = var(%d) = 1\n", config.StrategyVar))
	case "BAIT":
		sb.WriteString(fmt.Sprintf("triggerall = var(%d) = 3\n", config.StrategyVar))
	}

	// Distance condition
	if distCond != "" {
		sb.WriteString(fmt.Sprintf("triggerall = %s\n", distCond))
	}

	// Extra trigger conditions
	if extraTrigger != "" {
		sb.WriteString(fmt.Sprintf("triggerall = %s\n", extraTrigger))
	}

	sb.WriteString("trigger1 = ctrl\n")

	sb.WriteString("\n")

	// Set cooldown after using this move
	sb.WriteString(fmt.Sprintf("[State -1, AI Cooldown Set: %s]\n", label))
	sb.WriteString("type = VarSet\n")
	sb.WriteString(fmt.Sprintf("triggerall = %s\n", config.AIActivation))
	sb.WriteString(fmt.Sprintf("trigger1 = StateNo = %d\n", stateID))
	sb.WriteString("trigger1 = Time = 0\n")
	sb.WriteString(fmt.Sprintf("v = %d\n", config.CooldownVar))
	sb.WriteString(fmt.Sprintf("value = %d\n", cooldownSet))
	sb.WriteString("\n")

	// Track last used state
	sb.WriteString(fmt.Sprintf("[State -1, AI Track: %s]\n", label))
	sb.WriteString("type = VarSet\n")
	sb.WriteString(fmt.Sprintf("triggerall = %s\n", config.AIActivation))
	sb.WriteString(fmt.Sprintf("trigger1 = StateNo = %d\n", stateID))
	sb.WriteString("trigger1 = Time = 0\n")
	sb.WriteString(fmt.Sprintf("v = %d\n", config.StateTrackVar))
	sb.WriteString(fmt.Sprintf("value = %d\n", stateID))
	sb.WriteString("\n")

	return sb.String()
}

// comboFollowupBlock generates a combo follow-up ChangeState.
func comboFollowupBlock(config *AIConfig, fromState, toState int, label string) string {
	return fmt.Sprintf(`
; --- Combo Follow-up: %d -> %d (%s) ---
[State -1, AI Combo: %s]
type = ChangeState
value = %d
triggerall = %s
triggerall = RoundState = 2
triggerall = StateNo = %d
triggerall = MoveContact
trigger1 = Random < 800

`, fromState, toState, label, label, toState,
		config.AIActivation, fromState)
}

// guardBlock generates the AI guard/block controller.
func guardBlock(config *AIConfig) string {
	en := enemyFunc(config)
	return fmt.Sprintf(`
; -------------------------------------------------------
; AI GUARD (DEFENSE)
; AI blocks when enemy is attacking at close range
; -------------------------------------------------------
[State -1, AI Guard]
type = ChangeState
value = 120
triggerall = %s
triggerall = RoundState = 2
triggerall = var(%d) = 1
triggerall = InGuardDist
triggerall = ctrl
trigger1 = %s, MoveType = A
trigger2 = %s, NumProj > 0

[State -1, AI Crouch Guard]
type = ChangeState
value = 152
triggerall = %s
triggerall = RoundState = 2
triggerall = var(%d) = 1
triggerall = InGuardDist
triggerall = ctrl
triggerall = %s, MoveType = A
trigger1 = Random < 400
trigger1 = %s, Pos Y >= 0

`, config.AIActivation, config.StrategyVar,
		en, en,
		config.AIActivation, config.StrategyVar,
		en, en)
}

// movementBlock generates AI movement controllers.
func movementBlock(config *AIConfig) string {
	en := enemyFunc(config)
	
	levelVar := "1" // default fallback if no AILevel allocated
	if l, ok := config.VarAllocation["AILevel"]; ok {
		levelVar = fmt.Sprintf("var(%d)", l)
	}

	return fmt.Sprintf(`
; -------------------------------------------------------
; AI MOVEMENT & SPACING (Xiangfei-ROTD Standard)
; -------------------------------------------------------

[State -1, AI Distance 0 Deadlock Breaker]
type = ChangeState
value = 905 ; Roll Back
triggerall = %s > 0 && roundstate = 2 && statetype != A
triggerall = p2bodydist X <= 0 && %s, statetype != L
trigger1 = ctrl || stateno = 0 || stateno = 20 || stateno = 21 || stateno = 22
trigger1 = time > 60
trigger1 = random <= %s * 50

[State -1, AI Roll Forward / Evade]
type = ChangeState
value = 900
triggerall = %s > 0 && roundstate = 2
triggerall = %s, movetype = A
triggerall = %s, backedgedist > 10 || p2bodydist X >= 100
triggerall = p2bodydist X = [0,150]
trigger1 = random <= %s * 25
trigger1 = ctrl

[State -1, AI Dash Forward]
type = ChangeState
value = 100
triggerall = %s 
triggerall = RoundState = 2
triggerall = ctrl
triggerall = StateType = S
trigger1 = p2bodydist X >= 160
trigger1 = random <= %s * 60

[State -1, AI Walk Forward]
type = ChangeState
value = 20
triggerall = %s
triggerall = RoundState = 2
triggerall = ctrl
triggerall = StateType = S
trigger1 = p2bodydist X > 60 || %s, statetype = L || %s, statetype = A
trigger1 = random <= %s * 80

[State -1, AI Walk Backward]
type = ChangeState
value = 22
triggerall = %s > 3 && roundstate = 2
triggerall = !inguarddist
trigger1 = ctrl || stateno = 21
trigger1 = p2bodydist X = [-5,50]
trigger1 = random <= %s * 30 || (p2bodydist X < 10)
trigger1 = backedgedist > 10
`, levelVar, en, levelVar, 
   levelVar, en, en, levelVar, 
   config.AIActivation, levelVar,
   config.AIActivation, en, en, levelVar,
   levelVar, levelVar)
}
