// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCharacter(arg1:string):Promise<string>;

export function ApplyPatch(arg1:string,arg2:string):Promise<string>;

export function GenerateReport(arg1:string):Promise<string>;

export function LoadStyles():Promise<string>;

export function PreviewStyle(arg1:string):Promise<string>;

export function SelectCharacter():Promise<string>;
