// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCharacter(arg1) {
  return window['go']['main']['App']['AnalyzeCharacter'](arg1);
}

export function ApplyPatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyPatch'](arg1, arg2);
}

export function GenerateReport(arg1) {
  return window['go']['main']['App']['GenerateReport'](arg1);
}

export function LoadStyles() {
  return window['go']['main']['App']['LoadStyles']();
}

export function PreviewStyle(arg1) {
  return window['go']['main']['App']['PreviewStyle'](arg1);
}

export function SelectCharacter() {
  return window['go']['main']['App']['SelectCharacter']();
}
